name: Pytest
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Run-Python-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

       # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.x"
      - name: Installe pip
        run: sudo apt install python3-pip
      - run: pwd
      - run: ls -l
      - run: pip install pytest
      - name: Lance les tests python
        run: pytest ${{ github.workspace }}